export const FETCH_SCRIPTS_START = 'FETCH_SCRIPTS_START'
export const FETCH_SCRIPTS_SUCCESS = 'FETCH_SCRIPTS_SUCCESS'
export const FETCH_SCRIPTS_FAILURE = 'FETCH_SCRIPTS_FAILURE'

export const FETCH_SCRIPT_BY_ID_START = 'FETCH_SCRIPT_BY_ID_START'
export const FETCH_SCRIPT_BY_ID_SUCCESS = 'FETCH_SCRIPT_BY_ID_SUCCESS'
export const FETCH_SCRIPT_BY_ID_FAILURE = 'FETCH_SCRIPT_BY_ID_FAILURE'

export const EDIT_QUESTION_ID = 'EDIT_QUESTION_ID'
export const INCREMENT_QUESTION_ID = 'INCREMENT_QUESTION_ID'

export const ANSWER_ID = 'ANSWER_ID'

export const LOGIN = 'LOGIN'

export const ADD_NEW_ANSWER = 'ADD_NEW_ANSWER'